log-pipeline:
  source:
    otel_logs_source:
      port: 21892
      ssl: false

  sink:
    - opensearch:
        hosts:
          - "http://opensearch:9200"
        index: "logs-${serviceName}"
        # 서비스 별로 인덱스 생성 (serviceName 변수 사용)

trace-pipeline:
  source:
    otel_trace_source:
      port: 21890
      ssl: false

  processor:
    - otel_traces:
    
  sink:
    - opensearch:
        hosts:
          - "http://opensearch:9200"
        index: "otel-v1-apm-span"
        insecure: true